version: '3.8'
services:
    database:
        image: 'postgres:alpine'
        container_name: '${DOCKER_PROJET_NAME}_postgres'
        environment:
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
            POSTGRES_DB: '${DOCKER_PROJET_NAME}_db'
        ports:
            - '5434:5432'