<?php

namespace App\Form;

use App\Entity\Solde;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class SoldeType extends AbstractType
{

    private $urlGenerator;

    public function __construct(UrlGeneratorInterface $urlGenerator)
    {
        $this->urlGenerator = $urlGenerator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('data1', null, ['attr' => [
                'data-action' => 'change->solde-form#record',
                'data-record-url' => $this->urlGenerator->generate('recordOK'),
            ],])
            ->add('data2')
            ->add('data3');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Solde::class,
        ]);
    }
    public function getBlockPrefix()
    {
        return ""; // TODO: Change the autogenerated stub
    }
}
